services:
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db

  api:
    image: postgrest/postgrest:v9.0.1
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_AUTHENTICATOR_USERNAME}:${POSTGRES_AUTHENTICATOR_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
      PGRST_DB_SCHEMAS: gazetteer
      PGRST_DB_ANON_ROLE: public_user
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  web:
    image: scar/scar-gazetteer:latest
    build: ./scar-gazetteer
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  dbdata:
