services:
  db:
   image: postgis/postgis:17-3.5
   ports:
     - "5432:5432"
   environment:
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   volumes:
     - dbdata:/var/lib/postgresql/data
     - ./database/roles.sql:/docker-entrypoint-initdb.d/11-roles.sql
     - ./database/schema.sql:/docker-entrypoint-initdb.d/12-schema.sql

  api:
    image: postgrest/postgrest:v14.1
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      PGRST_DB_SCHEMAS: gazetteer
      PGRST_DB_ANON_ROLE: public_user
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_PRE_REQUEST: gazetteer.authenticate
      PGRST_OPENAPI_SECURITY_ACTIVE: true
      PGRST_OPENAPI_SERVER_PROXY_URI: https://apps.aad.gov.au/scar-cga/api
    depends_on:
      - db
  
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    environment:
      SWAGGER_JSON_URL: http://localhost:3000
    depends_on:
      - api

volumes:
  dbdata:
