version: '3.7'

services:
    web:
      image: scar/scar-gazetteer:latest
      build: ./scar-gazetteer
    api:
      image: postgrest/postgrest:latest
      environment:
        - PGRST_DB_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        - PGRST_DB_SCHEMA=gazetteer
        - PGRST_DB_ANON_ROLE=${DATABASE_ANON_ROLE}
        - PGRST_JWT_SECRET=${JWT_SECRET}
        - PGRST_LOG_LEVEL=info
        - PGRST_PRE_REQUEST=gazetteer.authenticate
